### ISSUE TITLE
Firmware with Custom Feature Set.

### ISSUE THREAD

**Issue by Sergio-** [spm81/Quansheng_UV-K5#1]
Hi. Good day.
First of all, Thanks for organizing these firmware files. That's very useful resource. ;-)
I'm wondering if it's possible to have a v4.00.01 for UV-5R Plus that enables the AM modulation for up to 850Mhz frequency?
I'd like to have few other features enabled like the Battery Icon, the possibility to TX on all possible range, the rssi sbar, etc.
I'm not sure how to proceed to create such combination. I appreciate if you can guide/point how to make that.
Thanks a lot.

**Comment by spm81** [comment]
You just have to use uvmod kitchen and replace 2_01_26 file with the rssi v4 file ....
