### ISSUE TITLE
5 KHz step gone on new cfw AM receive 

### ISSUE THREAD

**Issue by Josh380** [spm81/Quansheng_UV-K5#10]
Much of the low band spectrum is lost due to no 5 khz step. Cannot tune in certain CB channels or tune in to most stations that end in zero, unless it happens to land on one of the other step settings.

PLEASE BRING BACK THE 5 KHZ STEP!

**Comment by jepotter224** [comment]
Hi Josh380,

I've loaded the latest CFW_by_OneOfEleven_VOEFW-d449cc0_ALL_TX.bin and it does not have step for 5 Khz as you report.
Possibly as a workaround the 1.25 Khz or 2.50 Khz could help that are listed?

**Comment by Josh380** [comment]
The problem with this, is that it skips a lot of the frequencies I want to tune into. Really need the 5khz back, then it would be perfect. Should not have been left out of the list.

**Comment by spm81** [comment]
what file ? where ? from who ?

**Comment by Josh380** [comment]
Spm81:

CFW_by_OneOfEleven_VOEFW-d449cc0_ALL_TX.bin

**Comment by Josh380** [comment]
This has not been solved yet. The new update still leaves out the 5 khz step.
