### ISSUE TITLE
COMPND icon not show in screen when is active RX TX

### ISSUE THREAD

**Issue by Yag00000** [spm81/Quansheng_UV-K5#11]
compresor COMPND icon not show in memory mode screen when is active RX TX  , in the original firmware 1of11 shows !!!

**Comment by subsubl** [comment]
> compresor COMPND icon not show in memory mode screen when is active RX TX , in the original firmware 1of11 shows !!!

Whats the problem?

**Comment by Yag00000** [comment]
the icon only shows C in VFO mode , not in memory mode like in 1of11

**Comment by spm81** [comment]
...
