### ISSUE TITLE
MCFW V0.15A and V0.16A

### ISSUE THREAD

**Issue by mpmdembi** [spm81/Quansheng_UV-K5#15]
ALL TX is not working. I can not enable TX for CB band.

**Comment by subsubl** [comment]
Works for me.

**Comment by jepotter224** [comment]
Hi subsubl,

Your report cb works fine, would you confirm other bands work fine please?
10 meter 28.0 thru 29.7, 15 meter 21.0 thru 21.9, 6 meter 50.0 thru 54.0

Also, if using these with AM (vs FM) do they work fine as well?

**Comment by spm81** [comment]
ALL TX TX in all band
go to secret menu (PTT+FN1 and turn on) and put it on

**Comment by mpmdembi** [comment]
> ALL TX TX in all band go to secret menu (PTT+FN1 and turn on) and put it on

Thanks for your reply! I checked in secret menu and there is TX 200, 350, 500 but no others like CB. Of course all of them are on.

**Comment by subsubl** [comment]
Close the thread. Batt is fixed in new version, ALLTX FW works when no F-Lock is selected in secret menu.

**Comment by mpmdembi** [comment]
> Close the thread. Batt is fixed in new version, ALLTX FW works when no F-Lock is selected in secret menu.

I have F-Lock set to off and no option to TX on CB band (for example). All bands enabled in a secret menu. What I can do else to enable it?

**Comment by jepotter224** [comment]
Hi mpmdembi,

Please add whether you are attempting to tx cb in AM or FM.

I do not believe the UV-K5 can tx in AM but only RX.

**Comment by mpmdembi** [comment]
> Hi mpmdembi,
> 
> Please add whether you are attempting to tx cb in AM or FM.
> 
> I do not believe the UV-K5 can tx in AM but only RX.

Hi!
Of course I tested in FM. In latest FW (0.21A) it starts to transmit on CB band, so this problem is solved :-)
Still I have whole time full battery icon and now I have 56% of battery :-(

**Comment by spm81** [comment]
will be fixed
