### ISSUE TITLE
are these mods based on v2.01.26?

### ISSUE THREAD

**Issue by RE3CON** [spm81/Quansheng_UV-K5#2]
are these all based on k5_v2.01.26 firmware and firmware version spoofed, I mean for the different models the version string overwritten or directly edited newer firmware versions?

**Comment by spm81** [comment]
Yes, they all based on k5_v2.01.26 firmware

**Comment by RE3CON** [comment]
they can easily made with my [online generator](https://recon.ddns.net/) an enhanced patcher version from whosmat's uvmod
I will do an universal search replace pattern patcher to transfer these mod features to newer and upcoming versions soon.
Keep it up mate!
Thanks

**Comment by spm81** [comment]
https://whosmatt.github.io/uvmod/

**Comment by RE3CON** [comment]
a bit different from my version.
