### ISSUE TITLE
SQ tail noise

### ISSUE THREAD

**Issue by rai4424** [spm81/Quansheng_UV-K5#20]
From all other radios  I m listening SQUELCH tail noise.  Before Custom FW there was no any SQ tail noise in my walkie talkie from Tx of Baofeng radio  or from K5.

**Comment by rai4424** [comment]
Keeping STE on receiving no any noise from a k5 and a baofeng but disctibed two walkie-talkies are receiving SQ tail noise from my UVk5 in which custom FW is installed.

**Comment by spm81** [comment]
Tell me after witch Version you notice that

**Comment by rai4424** [comment]
> Tell me after witch Version you notice that

Good to say to you that STE is working now on Tx and Rx in v.29c

**Comment by rai4424** [comment]
> Tell me after witch Version you notice that

Priviously I was using v.15

**Comment by rai4424** [comment]
New versions has been released, there are different issues now.
