### ISSUE TITLE
1o11_fagci_spectrum_v0.12_packed.bin - Scan issue

### ISSUE THREAD

**Issue by Cmed1967** [spm81/Quansheng_UV-K5#21]
When scanning and the radio receives a transmission, the channel the scan stops on does not reflect the actual channel the transmission is being received on.

Example: Scanning stops on channel 3, but the transmission being received is from another channel.

A possible complication is how should the behavior work if the received channel is one that is set as a priority channel.

**Comment by spm81** [comment]
that firmware is not mine
