### ISSUE TITLE
uv-k5-firmware-fagci-mod-v1.2.1.bin isn't fixed

### ISSUE THREAD

**Issue by schinfo** [spm81/Quansheng_UV-K5#24]
uv-k5-firmware-fagci-mod-v1.2.1.bin isn't fixed

_Originally posted by @schinfo in https://github.com/spm81/Quansheng_UV-K5/issues/22#issuecomment-1784047521_

**Comment by schinfo** [comment]
The 1750HZ sound is not transmitted - only noise is transmitted

**Comment by schinfo** [comment]
I cann't open any relais (70cm / 2m)

**Comment by spm81** [comment]
uv-k5-firmware-fagci-mod-v1.2.1.bin is not mine ... sorry
