### ISSUE TITLE
No update of OneofEleven with spectrum analyzer 

### ISSUE THREAD

**Issue by rai4424** [spm81/Quansheng_UV-K5#25]
No update of OneofEleven with spectrum analyzer since long time.

**Comment by spm81** [comment]
i know, you have egzumer firmware... old Spectrum but it works! 
the facgi Spectrum now don't fite on oneofeleven now

**Comment by rai4424** [comment]
I was wating for
A= Based on OneofEleven FW
with fugci spectrum analyzer

**Comment by rai4424** [comment]
Thankyou
