### ISSUE TITLE
_k5-fagci-mod with Quansheng UV 5R not works on full power TX

### ISSUE THREAD

**Issue by Romm67** [spm81/Quansheng_UV-K5#27]
I try many versions uv_k5 and _k5
TX power in H mode more low than in original firmware. 
How I can change it?

**Comment by spm81** [comment]
Use MCFW_V1.0_CAL

Download Link:
https://github.com/spm81/Quansheng_UV-K5/blob/main/Firmware/UNIVERSAL%20FIRMWARE%20(%20All%20Radios%20-%20UV-K5%2C%20UV-K5(8)%2C%20UV-K6%2C%20UV-5R%20Plus%2C%20etc...)/Custom%20Firmware%20by%20Matoz/MCFW_V1.0_CAL.bin

**Comment by Romm67** [comment]
Thank you! I'll try. Don't known how it works and find instruction

**Comment by aszcpl15** [comment]
New to all this, please bare with me.  How do I find the UNLOCK code?  Thanks.

**Comment by aszcpl15** [comment]
> Thank you! I'll try.

Is there UNLOCK Code?

**Comment by Romm67** [comment]
123400

**Comment by aszcpl15** [comment]
Thank you.
