### ISSUE TITLE
uv-k5-firmware-fagci-mod main 5.11.23 v1.bin on UV-K5(8)

### ISSUE THREAD

**Issue by gabriellazarescu** [spm81/Quansheng_UV-K5#29]
Hello, I get "The file version is error" on trying to load this file "uv-k5-firmware-fagci-mod main 5.11.23 v1.bin", which I guess is the latest version from fagci. This is the only file I get this error, I had no issues on loading other versions. For now I'm using the uv-k5-firmware-fagci-mod-v1.2.1-b6.bin. Did anybody tried this? Thank you!

**Comment by gabriellazarescu** [comment]
It worked! Thank you very much! My respects!

**Comment by jepotter224** [comment]
When understood as working, suggest Originator then to close issue please
