### ISSUE TITLE
Excluding the current frequency -  Spectru mod - Matoz

### ISSUE THREAD

**Issue by usernamefoo** [spm81/Quansheng_UV-K5#30]
In the Matoz mod, excluding the current frequency from scanning in the spectrum analyzer  isn't working. It just turns the squelch all the way up.   

... Just messing around with .32C, the frequency is excluded but some times the squelch just all the way to the top. I can get the analyzer to respond again by holding down the F key for a bit. Just a minor bug it seems.

**Comment by spm81** [comment]
You may have something there... a transmitter or something like that interfering with that frequency...
try another place
