### ISSUE TITLE
Some small bugs.

### ISSUE THREAD

**Issue by LZ1PPL** [spm81/Quansheng_UV-K5#33]
On firmware "Custom_Firmware_by_Matoz_V0.33.0C_fagci_keys_style.bin"
When you go to spectrum analyzer mode and press PTT you go to (I'm not Shure how this mode is called, but lets call it direct frequency mode), and if you try to change the modulation there the radio freezes. the buttons stop working and the only thing that can help is power off and back on.
The other thing is, when you go the the menu, and if the first menu item on screen is Squelch, it shows 0 , no Mather what level it actually is. If you scroll away and come back on Squelch, it shows the correct setting.
I have checked version "Custom_Firmware_by_Matoz_V0.31.9C_fagci_keys_style.bin" on this version everting is working fine.

**Comment by spm81** [comment]
The Squelch bug i know it ... The other i have to check it...
Thanks for reporting 🙏
