### ISSUE TITLE
DCS nie działa

### ISSUE THREAD

**Issue by uw5elk** [spm81/Quansheng_UV-K5#4]
In this modification, everything is fine, but reception (decoding) of signals from DCS does not work.

**Comment by spm81** [comment]
what modification ? witch file/firmware ?

**Comment by uw5elk** [comment]
> what modification ? witch file/firmware ?

https://github.com/spm81/Quansheng_UV-K5/blob/main/Firmware/UV-K5/_k5-fagci-mod-20230912_0118.bin

**Comment by spm81** [comment]
ok ... Try the new one here https://github.com/spm81/Quansheng_UV-K5/blob/main/Firmware/UNIVERSAL%20FIRMWARE%20(%20All%20Radios%20-%20UV-K5%2C%20UV-K5(8)%2C%20UV-K6%2C%20UV-5R%20Plus%2C%20etc...)/Open%20Spectrum%20Firmware%20by%20facgi/_k5-fagci-mod-20230926_1516.bin

**Comment by uw5elk** [comment]
Unfortunately...
