### ISSUE TITLE
Lost all frequencies below 29.0000 after uploading k5-fagci-mod-20230911_1510.bin

### ISSUE THREAD

**Issue by jepotter224** [spm81/Quansheng_UV-K5#5]
Having used CHIRP modified no-limit (python) for uploading .img file to Quansheng UV-K5 with frequencies in 26. (11 meter) or 28 (10 meter) to find that after loading any version k5-fagci-mod-20230911_1510.bin or later bins those 10 and 11 meter channels become frequency 108.000.

Can still use spectrum analyzer to go down to frequency 18.000 without issue and can VFO down to 18.000 as well, just MR (memory) channels are impacted.

Work around is to reload firmware back to k5-fagci-mod-20230831_0305.bin then can go up to firmware k5-fagci-mod-20230909_1515 and the 10 and 11 meter references return.

Thank you for the work on these mods, greatly appreciated!  (I'm an old IBM Assembler programmer from the IBM-TPF days and have done a far amount of QA over the last 12 years as well so I can appreciate your efforts in making a difference and hope to help in your successes as other had helped in mine)

**Comment by spm81** [comment]
i upload the last facgi Firmwares, maybe that problem is fix now
Please feel free to joing Fagni Topic Group @ Telegram https://web.telegram.org/k/#@quansheng_uvk5_en_dev here you can contact with him directly

**Comment by jepotter224** [comment]
Hi Facgi,

Thank you for the quick turnaround with updated mod firmware to test.

I tried all 4 updates dated from 9-25 and 9-26, issue remains of any frequency in MR below 29 mhz then display as if changed to 108.0000.

It's as if there is original logic that tests for lower frequency use and changes the display of them to 108.000 in the firmware loaded.  Maybe the earlier mod firmware logic over-riding this has a branch for it missing from SCM? 

Maybe this helps.

**Comment by jepotter224** [comment]
Hi Facgi,

Big thanks for the time, energy and attention on this!

The MR frequencies below 29 again show up on your _k5-fagci-mod-20230927_1644.bin file.

Also, thank you for also providing the MDF Name and Frequency display.
Stay well, John

**Comment by jepotter224** [comment]
Hi Facgi,

An update, this seems any use in your spectrum analyzer in yours or others firmwares will not display any memory channel with a frequency below 29 Mhz. I've firmware loaded your recent and other's recent to find this.

In using Chirp I download the memory file and it lists those channels with the below 29 Mhz frequency assigned, so that indicates the memory in the radio is unchanged, only the display of that below 29 Mhz is off.

I hope this helps

**Comment by jepotter224** [comment]
Hi Facgi,

With today's release by bu egzumer - 1o11_fagci_spectrum_v0.3_packed.bin now the below 29 MHZ are displaying with the programmed frequency as usual.

Thanks to you both for the fix.

**Comment by jepotter224** [comment]
Only item left is the related  UV-R5 Plus 'File version is not match' results, so Owners of the UV-R5 Plus version are unable to load using the PCPS software with the last firmwares.

**Comment by jepotter224** [comment]
Thank you Facgi for the fixes on your k5-fagci-mod-20231005_0117.bin firmware.

I've been able to update firmware on the UV-R5 Plus again as usual.

**Comment by jepotter224** [comment]
This closes the issue with appreciation for the effort put forth.
