### ISSUE TITLE
Menu Error - SCR

### ISSUE THREAD

**Issue by subsubl** [spm81/Quansheng_UV-K5#6]
The menu item SCR used for selecting the scrambler from 1 to 7 now has twice off, x, tx/rx, and another empty space with additional off.

Probably confusion with the screen and scrambler when somebody did the new menu, the error persists throughout all firmware with the new horizontal menu. 

Otherwise pretty solid! 
Cheers

**Comment by lohtse** [comment]
> The menu item SCR used for selecting the scrambler from 1 to 7 now has twice off, x, tx/rx, and another empty space with additional off.
> 
> Probably confusion with the screen and scrambler when somebody did the new menu, the error persists throughout all firmware with the new horizontal menu.
> 
> Otherwise pretty solid! Cheers

No such issue there for me... Try making sure you are in latest.... It will say SCRAM  not SCR now as well

**Comment by subsubl** [comment]
MatozFW
MCFW V0.01 to MCFW V0.05 Tested, same issue.

**Comment by spm81** [comment]
Thanks ... Will try to fix it later...
👍

**Comment by spm81** [comment]
Fixed

**Comment by spm81** [comment]
Fixed
