### ISSUE TITLE
CB Disabled on tx with dummy load with firmware: CFW_by_OneOfEleven_VOEFW-d449cc0_ALL_TX.bin

### ISSUE THREAD

**Issue by jepotter224** [spm81/Quansheng_UV-K5#7]
Hi CFW,

Everyone likes the AM fix work, thank you!

In using the newest firmware: CFW_by_OneOfEleven_VOEFW-d449cc0_ALL_TX.bin with a dummy load test on the CB frequencies the display shows TX DISABLE.  Any other 29 mhz and below, like 17M, will TX.

This was being done on a Quansheng UV-R5 Plus HT.

Was there a purpose for this?

Please advise.

**Comment by spm81** [comment]
Did you try newest versions ? It make the same?

**Comment by jepotter224** [comment]
I downloaded and installed CFW_by_OneOfEleven_VOEFW-618d696_ALL_TX.bin successfully, but the CB frequency still reports TX Disable on my UV-K5 thru a dummy load test.

**Comment by jepotter224** [comment]
New test discovered it has to do with dummy load test with modulation set for AM......found on CB and 17M.

I hope this helps.

**Comment by jepotter224** [comment]
Thank you fo the latest work in transmit to dummy load no longer shows TX DISABLE.
