### ISSUE TITLE
Tunas bug reported - On Custom_Firmware_by_Matoz_V0.07.bin new menu style has the same title on 56 & 58

### ISSUE THREAD

**Issue by jepotter224** [spm81/Quansheng_UV-K5#8]
On the Custom_Firmware_by_Matoz_V0.07.bin the ALLTX new menu style shows ALLTX on both menu number 56 and 58. Only the menu number can be changed the 58 won't change.

Possibly 58 is not suppose to be listed?

**Comment by spm81** [comment]
it's a bug from Tunas New Menu :( 
Sorry.... V0.08 is there to Download now :P

**Comment by jepotter224** [comment]
Thank you Tunas, the Custom_Firmware_by_Matoz_V0.14A.bin appears to have corrected the repeat on ALLTX...is now reads TX with ON or OFF selection.
