### ISSUE TITLE
Poor RX on UHF band or unaccurate S-meter

### ISSUE THREAD

**Issue by ct1esj** [spm81/Quansheng_UV-K5#9]
Congratulations on the excellent work, especially in AM, now with an outstanding RX, but in this latest version of two days ago "VOEFW-618d696.bin ", the RX in the UHF band is very poor, I have a 439.100MHz repeater nearby. which reaches me full scale, now i receive it with 1 S-meter unit. Overall it is 5 Stars, keep going.. Acho que o problema reside na calibração do S-meter.
Telegram @CT1ESJ

**Comment by spm81** [comment]
Amanhã vejo isso melhor, entretanto dá feedback no grupo https://t.me/PMR446PT

**Comment by ct1esj** [comment]
Já dei feedback,entretanto instalei a última versão CFW_by_OneOfEleven_V1of11-e0aa1a8.bin e tenho a dizer que está TOP, a questão do s-meter em UHF corrigida e agrada-me o s-meter, mas para me agradar mais ainda era o mesmo ser idêntico ao do Kenwood TH-D72, hihihi. Obrigado
